// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Matsuya-Web-API": v2 Resource Client
//
// Command:
// $ goagen
// --design=github.com/makotia/Matsuya-Web-API/design
// --out=$(GOPATH)/src/github.com/makotia/Matsuya-Web-API
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// RandomV2Path computes a request path to the random action of v2.
func RandomV2Path() string {

	return fmt.Sprintf("/v2/random")
}

// ランダムで松屋のメニュー名を返す
func (c *Client) RandomV2(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRandomV2Request(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRandomV2Request create the request corresponding to the random action endpoint of the v2 resource.
func (c *Client) NewRandomV2Request(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
