FORMAT: 1A
HOST: https://matsuya.makotia.me/

# Matsuya Web API

- 松屋のメニューに関するAPIです
- ランダムに返すAPIになっているため、APIを叩くたびに提供されるものが異なります  
- テストする際は `Production` モードにして実際のAPIを叩いてください  
- 近々メニュー名から詳細データを取れるようにするつもりです
- Apiaryの機能で各言語のサンプルが乗ってるのでそれコピペすれば多分動きます
- 追加してほしい機能やバグ報告、PullRequestsは[GitHub](https://github.com/mak0tia/Matsuya-Web-API)上でお願いします

## ランダムに返すAPI [/v3/random]

### すべてのメニューのデータをランダムに返してくるAPI [GET]

+ Response 200 (application/json)

        {
          "name":"豚バラ焼肉定食",
          "price":550,
          "calorie":773,
          "protein":25.9,
          "lipid":29.2,
          "carbohydrate":98.8,
          "sodium":1121,
          "saltEquivalent":2.8,
          "description":"ジューシーな豚バラを塩コショウでシンプルに！",
          "imageURL":"https://www.matsuyafoods.co.jp/menu/upload_images/tei_bara_yaki_r_161018.jpg"
        }