FORMAT: 1A
HOST: https://matsuya-api.herokuapp.com/

# Matsuya Web API

松屋のメニューをランダムに返すAPIと松屋のメニューから栄養素等を返すAPIです(後者は現在開発中)  
ランダムに返すAPIになっているため、APIを叩くたびに提供されるものが異なります  
テストする際は`Production`モードにして実際のAPIを叩いてください  
そうするときちんとした結果が得られて楽しいです

## ランダムに返すAPI [/v1/random]

### メインメニューのみをランダムに返してくるAPI [GET]

+ Response 200 (application/json)

        ["メニュー名"]

## すべてのメニューをランダムに返すAPI [/v1/random/all]

### すべてのメニュー(サイドメニューやドリンク含む)を返してくるAPI [GET]

+ Response 200 (application/json)

        ["メニュー名(ドリンク等含む)"]