version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
    environment:
      - NODE_MONGODB_CONNECTION_URL=db
      - NODE_MONGODB_CONNECTION_PORT=27017
      - NODE_MONGODB_CONNECTION_USER=matsuya
      - NODE_MONGODB_CONNECTION_PASS=matsuya
  db:
    build: ./migration
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=matsuya
    volumes:
      - './db:/data/db'

