version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    links:
      - db
    environment:
      - MONGODB_CONNECTION_URL=mongodb://matsuya:matsuya@db:27017/matsuya
  db:
    build: ./migration
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=matsuya
    volumes:
      - './db:/data/db'

