version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      - NODE_MONGODB_CONNECTION_URL=db
      - NODE_MONGODB_CONNECTION_PORT=27017
      - NODE_MONGODB_CONNECTION_USER=matsuya
      - NODE_MONGODB_CONNECTION_PASS=matsuya
  db:
    build: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=matsuya
      - MONGO_INITDB_ROOT_PASSWORD=matsuya
      - MONGO_INITDB_DATABASE=matsuya
    voluems:
      - './db:/data/db'

