
version: 2
jobs:
  test:
    working_directory: /go/src/github.com/makotia/Matsuya-Web-API
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mongodb:4.0
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -v ./...
      - run: go test -v -race ./...

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
