// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Matsuya-Web-API": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/makotia/Matsuya-Web-API/design
// --out=$(GOPATH)/src/github.com/makotia/Matsuya-Web-API
// --version=v1.3.1

package test
